/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/__root"
import { Route as SpacesRouteImport } from "./../routes/spaces"
import { Route as SidebarRouteRouteImport } from "./../routes/_sidebar/route"
import { Route as IndexRouteImport } from "./../routes/index"
import { Route as SidebarChatRouteImport } from "./../routes/_sidebar/chat"

const SpacesRoute = SpacesRouteImport.update({
  id: "/spaces",
  path: "/spaces",
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: "/_sidebar",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarChatRoute = SidebarChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/spaces": typeof SpacesRoute
  "/chat": typeof SidebarChatRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/spaces": typeof SpacesRoute
  "/chat": typeof SidebarChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_sidebar": typeof SidebarRouteRouteWithChildren
  "/spaces": typeof SpacesRoute
  "/_sidebar/chat": typeof SidebarChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/spaces" | "/chat"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/spaces" | "/chat"
  id: "__root__" | "/" | "/_sidebar" | "/spaces" | "/_sidebar/chat"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  SpacesRoute: typeof SpacesRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/spaces": {
      id: "/spaces"
      path: "/spaces"
      fullPath: "/spaces"
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_sidebar": {
      id: "/_sidebar"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_sidebar/chat": {
      id: "/_sidebar/chat"
      path: "/chat"
      fullPath: "/chat"
      preLoaderRoute: typeof SidebarChatRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarChatRoute: typeof SidebarChatRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarChatRoute: SidebarChatRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  SpacesRoute: SpacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
